### ISSUE TITLE
GoPro support

### ISSUE THREAD

**Issue by arekbulski** [seebk/GIMP-Lensfun#16]
I do not see GoPro on the list of camera producers. We need GoPro!

http://askubuntu.com/questions/797966/gopro-fisheye-lens-correction-free-software

**Comment by seebk** [comment]
On 13.07.2016 13:39, Arkadiusz Bulski wrote:
> I do not see GoPro on the list of camera producers. We need GoPro!
>

The support of cameras depends on the coverage of the underlying lensfun 
database and not in GimpLensfun itself. Please see 
http://wilson.bronger.org/lensfun_coverage.html and check if your camera 
is already profiled and part of the database. Otherwise, you will find 
some instructions about how you can help profiling at 
http://lensfun.sourceforge.net/calibration/

Sebastian

**Comment by arekbulski** [comment]
GoPro is listed under your link, but I do not see it in GIMP. Installed GIMP through apt-get not source btw.

**Comment by amtivey** [comment]
The availability of cameras in the drop down list depends on the CameraMakers list defined at gimplensfun.cpp:85, so even if the underlying lensfun version supports GoPro, you cannot select it in the plug-in.
