### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by havilson** [seebk/GIMP-Lensfun#17]
Hi, I installed the latest release as described and got the following error:
![lensfun_error](https://cloud.githubusercontent.com/assets/5696397/18014731/a3d6d350-6b9a-11e6-9029-07d7256f6f8f.png)

I'm using GIMP 2.8.18, Windows 10 Home (x64).

**Comment by Anoneemouse** [comment]
I got the same error after installing it today Oct 16, 2016.  I'm also using Windows 10 and Gimp 2.8.18.  It would be very nice if someone could fix whatever is causing this problem, or let us know what we need to do to install the plugin so it works.

**Comment by gadton** [comment]
Same for me! I've also tried a clean installation of GIMP without succes.
Feel free to contact me if someone needs detail information, dumps, etc.

**Comment by seebk** [comment]
Sorry, it seems the installer is no more compatible with the recent (64bit?) builds of GIMP. Unfortunately, there is no real maintainer of the Windows installer. That's why it is marked as experimental. 

If anyone has experience with building GIMP plugins on Windows, feel free to send an updated installer. Personally, I do not have the time to fix this at the moment.

**Comment by gadton** [comment]
Is it just the installer or the used libs? If it's the installer: could you describe which lib has to be placed in which folder?

**Comment by seebk** [comment]
The compiler and libraries I used for compilation are not compatible with 
the ones from gimp. But I could not find out which ones I have to use 
instead. So it is not as easy as just changing a few path names, unfortunately.

Gesendet mit AquaMail für Android
http://www.aqua-mail.com


Am 30. Oktober 2016 2:30:10 nachm. schrieb gadton <notifications@github.com>:

**Comment by seebk** [comment]
See #20
